import { BrowserModule, Title } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { ROUTING, AppRoutes } from './app.routing';
import { AppComponent } from './app.component';
import { ReactiveFormsModule,FormsModule } from '@angular/forms';
import { HttpClientModule, HttpClient } from '@angular/common/http';
import { ToastrModule } from 'ngx-toastr';
import { SignInComponent } from './core/login/sign-in/sign-in.component';
import { SignUpComponent } from './core/login/sign-up/sign-up.component';
import {DragulaModule , DragulaService} from "ng2-dragula/ng2-dragula"


import { environment } from '../environments/environment';
import { AngularFireModule } from 'angularfire2';
import { AngularFireDatabaseModule } from 'angularfire2/database';
import { AngularFireAuthModule } from 'angularfire2/auth';
import { AuthService } from './core/services/auth.service';
import { AuthGuardService } from './core/services/auth-guard.service';


import { RegisterUserComponent } from './core/login/register-user/register-user.component';
import { UserComponent } from './modules/user/user.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { LoadingBarRouterModule } from '@ngx-loading-bar/router';
import { PerfectScrollbarModule } from 'ngx-perfect-scrollbar';
import { PERFECT_SCROLLBAR_CONFIG } from 'ngx-perfect-scrollbar';
import { PerfectScrollbarConfigInterface } from 'ngx-perfect-scrollbar';
import { AgmCoreModule } from '@agm/core';
import { NgxDatatableModule } from '@swimlane/ngx-datatable';
import { NgDragDropModule } from 'ng-drag-drop';

import {
  MatSidenavModule,
  MatCardModule,
  MatMenuModule,
  MatCheckboxModule,
  MatIconModule,
  MatButtonModule,
  MatToolbarModule,
  MatTabsModule,
  MatListModule,
  MatSlideToggleModule,
  MatSelectModule,
  MatProgressBarModule } from '@angular/material';
import { FlexLayoutModule } from '@angular/flex-layout';
import {BidiModule} from '@angular/cdk/bidi';


import {
  MenuComponent,
  HeaderComponent,
  SidebarComponent,
  NotificationComponent,
  OptionsComponent,
  AdminLayoutComponent,
  AuthLayoutComponent,
  AccordionAnchorDirective,
  AccordionLinkDirective,
  AccordionDirective
} from './core';
import { UserProfileComponent } from './modules/user/user-profile/user-profile.component';
import { from } from 'rxjs';
import { CreateInvoiceComponent } from './modules/account/create-invoice/create-invoice.component';
import { InvoiceListComponent } from './modules/account/invoice-list/invoice-list.component';
import { UploadInvoiceComponent } from './modules/account/upload-invoice/upload-invoice.component';
import { InvoiceDetailsComponent } from './modules/account/invoice-details/invoice-details.component';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';



export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

const DEFAULT_PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  suppressScrollX: true,
  wheelSpeed: 2,
  wheelPropagation: true,
  minScrollbarLength: 20
};

export const fireBaseLoginConfig = {
provider : '',
method : ''

}


@NgModule({
  declarations: [
    AppComponent,
    SignInComponent,
    SignUpComponent,
    RegisterUserComponent,
    UserComponent,
    HeaderComponent,
    SidebarComponent,
    NotificationComponent,
    OptionsComponent,
    MenuComponent,
    AdminLayoutComponent,
    AuthLayoutComponent,
    AccordionAnchorDirective,
    AccordionLinkDirective,
    AccordionDirective,
    UserProfileComponent,
    AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,
    ReactiveFormsModule,
    ROUTING,
    // ToastrModule.forRoot({
    //   timeOut: 2000,
    //   positionClass: 'toast-bottom-right',
    //   preventDuplicates: true,
    // }),
    ToastrModule.forRoot(),
    FormsModule,
    BrowserAnimationsModule,
    RouterModule.forRoot(AppRoutes),
    HttpClientModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader),
        deps: [HttpClient]
      }
    }),
    DragulaModule,
    LoadingBarRouterModule,
    MatSidenavModule,
    MatCardModule,
    MatMenuModule,
    MatCheckboxModule,
    MatIconModule,
    MatButtonModule,
    MatToolbarModule,
    MatTabsModule,
    MatListModule,
    MatSlideToggleModule,
    MatSelectModule,
    MatProgressBarModule,
    FlexLayoutModule,
    BidiModule,
    NgxDatatableModule ,
    AgmCoreModule.forRoot({apiKey: 'YOURAPIKEY'}),
    PerfectScrollbarModule,
    AngularFireModule.initializeApp(environment.firbaseConfig),
    AngularFireDatabaseModule,
    AngularFireAuthModule,
    NgDragDropModule.forRoot()
  ],
  providers: [{
      provide: PERFECT_SCROLLBAR_CONFIG,
      useValue: DEFAULT_PERFECT_SCROLLBAR_CONFIG
    },
    Title,
    AuthService,
    AuthGuardService],
  bootstrap: [AppComponent]
})
export class AppModule { }
